# Generated by Django 4.1.7 on 2026-02-09 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('api_key', models.CharField(editable=False, max_length=128, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
