# Generated by Django 4.1.7 on 2026-02-12 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 19, 23, 30, 16, 108771, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
