# Generated by Django 4.1.7 on 2026-02-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_alter_apikey_expires_at_alter_apikey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
