# Generated by Django 4.1.7 on 2026-02-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0004_alter_apikey_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
